[package]
name = "AlleloPNM"
version = "0.1.0"
description = "Allelo PNM App"
authors = ["Niko Bonnieure"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "allelo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.0", features = [] }

[dependencies]
tauri = { version = "2.9.0", features = ["unstable"] }
tauri-plugin-log = "2"
log = "0.4"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-contacts-importer = { path = "../../tauri-plugin-contacts-importer/" }
serde_bare = "0.5.0"
serde_bytes = "0.11.7"
tauri-plugin-barcode-scanner = "2"
ng-repo = { path = "../../../engine/repo" }
ng-net = { path = "../../../engine/net" }
ng-wallet = { path = "../../../engine/wallet" }
nextgraph = { path = "../../../sdk/rust" }
oxrdf = { git = "https://git.nextgraph.org/NextGraph/oxigraph.git",  branch="main", features = ["rdf-star", "oxsdatatypes"] }
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
sys-locale = { version = "0.3.1" }
zeroize = { version = "1.7.0", features = ["zeroize_derive"] }
ng-async-tungstenite = {  git = "https://git.nextgraph.org/NextGraph/async-tungstenite.git", branch = "nextgraph",  features = ["async-std-runtime", "async-native-tls"] }
