[package]
name = "tauri-plugin-barcode-scanner"
version = "2.4.2"
description = "Scan QR codes, EAN-13 and other kinds of barcodes on Android and iOS"
edition = "2021"
links = "tauri-plugin-barcode-scanner"

[package.metadata.docs.rs]
targets = ["x86_64-linux-android"]

[package.metadata.platforms.support]
windows = { level = "none", notes = "" }
linux = { level = "none", notes = "" }
macos = { level = "none", notes = "" }
android = { level = "full", notes = "" }
ios = { level = "full", notes = "" }


[build-dependencies]
tauri-plugin = "2.4"

[dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = { version = "2.8.2", default-features = false }
serde_json = "1"

[target.'cfg(target_os = "ios")'.dependencies]
tauri = { version = "2.8.2", default-features = false, features = ["wry"] }
